spring.application.name=bechedhli-solar

# PostgreSQL (Supabase Pooler)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DB_USER:postgres.sdtpyzsauhkrreaulmom}
spring.datasource.password=${DB_PASSWORD:i9gdRmbQXKFQpkbY}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.datasource.hikari.connection-test-query=SELECT 1

# Server
server.port=${PORT:9090}

# GraphQL
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true