spring.datasource.url=jdbc:postgresql://db.sdtpyzsauhkrreaulmom.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=i9gdRmbQXKFQpkbY
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=false
