spring.application.name=bechedhli-solar
spring.datasource.url=jdbc:h2:mem:bechedhli
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
server.port=9090
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
